# Generated by Django 4.2.10 on 2024-03-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
