# Generated by Django 4.2.10 on 2024-03-12 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_report_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='image',
            new_name='file_upload',
        ),
        migrations.AddField(
            model_name='report',
            name='submission_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
