# Generated by Django 4.2.10 on 2024-03-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_report_submission_text_alter_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file_upload',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
