# Generated by Django 4.2.10 on 2024-03-13 02:45

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_report_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file_upload',
            field=models.FileField(blank=True, default=None, null=True, storage=storages.backends.s3.S3StaticStorage(), upload_to='uploads/'),
        ),
    ]
