# Generated by Django 4.2.10 on 2024-03-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_report_date_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_under_review',
            field=models.BooleanField(default=False),
        ),
    ]
