# Generated by Django 4.2.10 on 2024-03-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_report_is_under_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='is_under_review',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
