# Generated by Django 4.2.10 on 2024-03-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_report_submission_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='submission_text',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
