# Generated by Django 4.2.10 on 2024-03-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_report_submission_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='is_under_review',
            new_name='in_progress',
        ),
        migrations.AddField(
            model_name='report',
            name='seen',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
