# Generated by Django 4.2.10 on 2024-03-25 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_is_under_review_report_in_progress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='seen',
            new_name='is_seen',
        ),
    ]
