# Generated by Django 4.2.10 on 2024-03-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_seen_report_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='explanation_text',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
